create extension if not exists pgcrypto;

create or replace function public.is_staff_user()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.user_profiles
    where id = auth.uid()
      and role in ('admin', 'editor')
  );
$$;

create table if not exists public.editor_collections (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  description text,
  cover_image text,
  badge_label text,
  collection_type text not null default 'manual'
    check (collection_type in ('manual', 'dynamic')),
  sort_mode text not null default 'manual'
    check (sort_mode in ('manual', 'popularity', 'score', 'recent')),
  status text not null default 'draft'
    check (status in ('draft', 'published', 'archived')),
  visibility text not null default 'public'
    check (visibility in ('public', 'private', 'unlisted')),
  item_limit integer not null default 12,
  is_featured boolean not null default false,
  starts_at timestamptz,
  ends_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.editor_collection_items (
  id bigint generated by default as identity primary key,
  collection_id bigint not null references public.editor_collections(id) on delete cascade,
  title_id bigint not null references public.canonical_titles(id) on delete cascade,
  position integer not null default 0,
  note text,
  created_at timestamptz not null default now(),
  unique (collection_id, title_id)
);

create table if not exists public.homepage_content_blocks (
  id bigint generated by default as identity primary key,
  block_key text not null unique,
  title text not null,
  subtitle text,
  block_type text not null default 'collection'
    check (block_type in ('hero', 'collection', 'manual_list', 'recommendation', 'continue', 'trending')),
  status text not null default 'draft'
    check (status in ('draft', 'published', 'archived')),
  visibility text not null default 'public'
    check (visibility in ('public', 'private')),
  collection_id bigint references public.editor_collections(id) on delete set null,
  position integer not null default 0,
  config jsonb not null default '{}'::jsonb,
  starts_at timestamptz,
  ends_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_editor_collections_status
on public.editor_collections(status, visibility, is_featured, updated_at desc);

create index if not exists idx_editor_collection_items_collection
on public.editor_collection_items(collection_id, position asc, created_at asc);

create index if not exists idx_editor_collection_items_title
on public.editor_collection_items(title_id);

create index if not exists idx_homepage_content_blocks_status
on public.homepage_content_blocks(status, visibility, position asc);

drop trigger if exists trg_editor_collections_updated_at on public.editor_collections;
create trigger trg_editor_collections_updated_at
before update on public.editor_collections
for each row
execute function public.set_updated_at();

drop trigger if exists trg_homepage_content_blocks_updated_at on public.homepage_content_blocks;
create trigger trg_homepage_content_blocks_updated_at
before update on public.homepage_content_blocks
for each row
execute function public.set_updated_at();

alter table if exists public.editor_collections enable row level security;
alter table if exists public.editor_collection_items enable row level security;
alter table if exists public.homepage_content_blocks enable row level security;

drop policy if exists "Public can read published collections" on public.editor_collections;
create policy "Public can read published collections"
on public.editor_collections for select
using (
  visibility = 'public'
  and status = 'published'
  and (starts_at is null or starts_at <= now())
  and (ends_at is null or ends_at >= now())
);

drop policy if exists "Staff can manage collections" on public.editor_collections;
create policy "Staff can manage collections"
on public.editor_collections for all
using (public.is_staff_user())
with check (public.is_staff_user());

drop policy if exists "Public can read published collection items" on public.editor_collection_items;
create policy "Public can read published collection items"
on public.editor_collection_items for select
using (
  exists (
    select 1
    from public.editor_collections c
    where c.id = editor_collection_items.collection_id
      and c.visibility = 'public'
      and c.status = 'published'
      and (c.starts_at is null or c.starts_at <= now())
      and (c.ends_at is null or c.ends_at >= now())
  )
);

drop policy if exists "Staff can manage collection items" on public.editor_collection_items;
create policy "Staff can manage collection items"
on public.editor_collection_items for all
using (public.is_staff_user())
with check (public.is_staff_user());

drop policy if exists "Public can read published homepage blocks" on public.homepage_content_blocks;
create policy "Public can read published homepage blocks"
on public.homepage_content_blocks for select
using (
  visibility = 'public'
  and status = 'published'
  and (starts_at is null or starts_at <= now())
  and (ends_at is null or ends_at >= now())
);

drop policy if exists "Staff can manage homepage blocks" on public.homepage_content_blocks;
create policy "Staff can manage homepage blocks"
on public.homepage_content_blocks for all
using (public.is_staff_user())
with check (public.is_staff_user());
