create table if not exists public.franchises (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  franchise_name text not null,
  aliases jsonb not null default '[]'::jsonb,
  source_provider text not null default 'manual',
  source_id text,
  source_title_count integer not null default 0,
  matched_title_count integer not null default 0,
  entry_type_counts jsonb not null default '{}'::jsonb,
  member_titles jsonb not null default '[]'::jsonb,
  unmatched_titles jsonb not null default '[]'::jsonb,
  raw_payload jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_synced_at timestamptz,
  unique (source_provider, source_id)
);

alter table public.franchises
  add constraint franchises_aliases_is_array_chk
  check (jsonb_typeof(aliases) = 'array');

alter table public.franchises
  add constraint franchises_entry_type_counts_is_object_chk
  check (jsonb_typeof(entry_type_counts) = 'object');

alter table public.franchises
  add constraint franchises_member_titles_is_array_chk
  check (jsonb_typeof(member_titles) = 'array');

alter table public.franchises
  add constraint franchises_unmatched_titles_is_array_chk
  check (jsonb_typeof(unmatched_titles) = 'array');

create table if not exists public.title_franchise_memberships (
  id bigint generated by default as identity primary key,
  franchise_id bigint not null references public.franchises(id) on delete cascade,
  canonical_title_id bigint not null references public.canonical_titles(id) on delete cascade,
  membership_order integer not null default 0,
  source_title text,
  source_provider text not null default 'manual',
  is_primary boolean not null default false,
  created_at timestamptz not null default now(),
  unique (franchise_id, canonical_title_id)
);

alter table public.canonical_titles
  add column if not exists franchise_id bigint references public.franchises(id) on delete set null,
  add column if not exists franchise_name text,
  add column if not exists franchise_aliases jsonb not null default '[]'::jsonb,
  add column if not exists franchises_cache jsonb not null default '[]'::jsonb;

alter table public.canonical_titles
  add constraint canonical_titles_franchise_aliases_is_array_chk
  check (jsonb_typeof(franchise_aliases) = 'array');

alter table public.canonical_titles
  add constraint canonical_titles_franchises_cache_is_array_chk
  check (jsonb_typeof(franchises_cache) = 'array');

create index if not exists idx_franchises_slug on public.franchises(slug);
create index if not exists idx_franchises_name on public.franchises(franchise_name);
create index if not exists idx_title_franchise_memberships_franchise_id
  on public.title_franchise_memberships(franchise_id);
create index if not exists idx_title_franchise_memberships_title_id
  on public.title_franchise_memberships(canonical_title_id);
create index if not exists idx_canonical_titles_franchise_id
  on public.canonical_titles(franchise_id);

create or replace function public.refresh_title_franchise_cache_for_title(v_title_id bigint)
returns void
language plpgsql
as $$
declare
  primary_franchise record;
begin
  if v_title_id is null then
    return;
  end if;

  select
    f.id,
    f.franchise_name,
    f.aliases
  into primary_franchise
  from public.title_franchise_memberships tfm
  join public.franchises f on f.id = tfm.franchise_id
  where tfm.canonical_title_id = v_title_id
  order by tfm.is_primary desc, tfm.membership_order asc, tfm.id asc
  limit 1;

  update public.canonical_titles ct
  set
    franchise_id = primary_franchise.id,
    franchise_name = primary_franchise.franchise_name,
    franchise_aliases = coalesce(primary_franchise.aliases, '[]'::jsonb),
    franchises_cache = coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'id', f.id,
          'slug', f.slug,
          'franchise_name', f.franchise_name,
          'aliases', f.aliases,
          'membership_order', tfm.membership_order,
          'is_primary', tfm.is_primary
        )
        order by tfm.is_primary desc, tfm.membership_order asc, tfm.id asc
      )
      from public.title_franchise_memberships tfm
      join public.franchises f on f.id = tfm.franchise_id
      where tfm.canonical_title_id = v_title_id
    ), '[]'::jsonb)
  where ct.id = v_title_id;
end;
$$;

create or replace function public.refresh_title_franchise_cache()
returns trigger
language plpgsql
as $$
begin
  perform public.refresh_title_franchise_cache_for_title(coalesce(new.canonical_title_id, old.canonical_title_id));
  return null;
end;
$$;

create or replace function public.refresh_title_franchise_cache_on_franchise_update()
returns trigger
language plpgsql
as $$
declare
  membership_row record;
begin
  for membership_row in
    select canonical_title_id
    from public.title_franchise_memberships
    where franchise_id = coalesce(new.id, old.id)
  loop
    perform public.refresh_title_franchise_cache_for_title(membership_row.canonical_title_id);
  end loop;

  return null;
end;
$$;

drop trigger if exists trg_title_franchise_cache_memberships on public.title_franchise_memberships;
create trigger trg_title_franchise_cache_memberships
after insert or update or delete on public.title_franchise_memberships
for each row
execute function public.refresh_title_franchise_cache();

drop trigger if exists trg_title_franchise_cache_franchises on public.franchises;
create trigger trg_title_franchise_cache_franchises
after update on public.franchises
for each row
execute function public.refresh_title_franchise_cache_on_franchise_update();

drop trigger if exists trg_franchises_updated_at on public.franchises;
create trigger trg_franchises_updated_at
before update on public.franchises
for each row
execute function public.set_updated_at();

update public.canonical_titles ct
set
  franchise_id = null,
  franchise_name = null,
  franchise_aliases = '[]'::jsonb,
  franchises_cache = '[]'::jsonb
where not exists (
  select 1
  from public.title_franchise_memberships tfm
  where tfm.canonical_title_id = ct.id
);
