create extension if not exists pgcrypto;

create table if not exists public.user_discover_saved_searches (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  label text,
  query text not null default '',
  tag text not null default '',
  scope text not null default 'all'
    check (scope in ('all', 'titles', 'posts', 'people', 'tierlists')),
  title_type text not null default 'all'
    check (title_type in ('all', 'anime', 'manga', 'manhwa')),
  pinned boolean not null default false,
  position integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists idx_user_discover_saved_searches_user_position
on public.user_discover_saved_searches(user_id, position, updated_at desc);

create index if not exists idx_user_discover_saved_searches_user_pin
on public.user_discover_saved_searches(user_id, pinned desc, updated_at desc);

drop trigger if exists trg_user_discover_saved_searches_updated_at on public.user_discover_saved_searches;
create trigger trg_user_discover_saved_searches_updated_at
before update on public.user_discover_saved_searches
for each row
execute function public.set_updated_at();

alter table if exists public.user_discover_saved_searches enable row level security;

drop policy if exists "Users can manage own discover saved searches" on public.user_discover_saved_searches;
create policy "Users can manage own discover saved searches"
on public.user_discover_saved_searches for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create table if not exists public.discover_search_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  session_id uuid,
  event_type text not null
    check (event_type in ('search_view', 'preset_apply', 'result_click', 'saved_search_create', 'saved_search_update', 'saved_search_delete')),
  query text not null default '',
  normalized_query text not null default '',
  scope text not null default 'all'
    check (scope in ('all', 'titles', 'posts', 'people', 'tierlists')),
  title_type text not null default 'all'
    check (title_type in ('all', 'anime', 'manga', 'manhwa')),
  tag text not null default '',
  preset_source text,
  result_type text
    check (result_type is null or result_type in ('titles', 'posts', 'people', 'tierlists')),
  result_id text,
  result_rank integer,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_discover_search_events_created_at
on public.discover_search_events(created_at desc);

create index if not exists idx_discover_search_events_type_created_at
on public.discover_search_events(event_type, created_at desc);

create index if not exists idx_discover_search_events_query
on public.discover_search_events(normalized_query, created_at desc);

create index if not exists idx_discover_search_events_result_type
on public.discover_search_events(result_type, created_at desc);

alter table if exists public.discover_search_events enable row level security;

drop policy if exists "Anyone can insert discover search events" on public.discover_search_events;
create policy "Anyone can insert discover search events"
on public.discover_search_events for insert
to anon, authenticated
with check (
  user_id is null or user_id = auth.uid()
);

drop policy if exists "Staff can read discover search events" on public.discover_search_events;
create policy "Staff can read discover search events"
on public.discover_search_events for select
using (public.is_staff_user());

drop policy if exists "Staff can manage discover search events" on public.discover_search_events;
create policy "Staff can manage discover search events"
on public.discover_search_events for all
using (public.is_staff_user())
with check (public.is_staff_user());
