-- ============================================================
-- Party Title Guess schema
-- 2026-04-03
--
-- Goal:
-- - keep catalog character data reusable
-- - add gameplay metadata to title_characters
-- - add curated set/question/clue tables for the Title Guess mode
-- - support 4 ordered clue cards without relying on protagonist clues
-- ============================================================

-- ----------------------------------------------------------------
-- 1. title_characters gameplay metadata
-- ----------------------------------------------------------------
alter table public.title_characters
  add column if not exists is_primary_protagonist boolean not null default false,
  add column if not exists is_guess_disabled boolean not null default false,
  add column if not exists guess_priority smallint not null default 0,
  add column if not exists guess_note text;

alter table public.title_characters
  drop constraint if exists title_characters_guess_priority_check;

alter table public.title_characters
  add constraint title_characters_guess_priority_check
  check (guess_priority between -10 and 10);

create index if not exists idx_title_characters_guess_pool
  on public.title_characters (
    canonical_title_id,
    is_guess_disabled,
    is_primary_protagonist,
    role,
    sort_order asc,
    guess_priority desc,
    id asc
  );

create index if not exists idx_title_characters_guess_enabled
  on public.title_characters (canonical_title_id, sort_order asc, id asc)
  where is_guess_disabled = false;

-- ----------------------------------------------------------------
-- 2. Title Guess set headers
-- ----------------------------------------------------------------
create table if not exists public.party_title_guess_sets (
  id bigint generated by default as identity primary key,
  owner_user_id uuid references auth.users(id) on delete set null,
  creator_name text not null default '',
  name text not null,
  description text,
  cover_url text,
  visibility text not null default 'public'
    check (visibility in ('public', 'unlisted', 'private')),
  is_official boolean not null default false,
  question_count integer not null default 0 check (question_count >= 0),
  like_count integer not null default 0 check (like_count >= 0),
  play_count integer not null default 0 check (play_count >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ----------------------------------------------------------------
-- 3. Title Guess questions
-- ----------------------------------------------------------------
create table if not exists public.party_title_guess_questions (
  id bigint generated by default as identity primary key,
  set_id bigint not null
    references public.party_title_guess_sets(id) on delete cascade,
  answer_title_id bigint not null
    references public.canonical_titles(id) on delete cascade,
  answer_aliases jsonb not null default '[]'::jsonb,
  difficulty_tier smallint not null default 2,
  status text not null default 'draft'
    check (status in ('draft', 'ready', 'archived')),
  sort_order integer not null default 0,
  source_strategy text not null default 'manual'
    check (source_strategy in ('manual', 'auto', 'hybrid')),
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (set_id, answer_title_id)
);

alter table public.party_title_guess_questions
  drop constraint if exists party_title_guess_questions_difficulty_tier_check;

alter table public.party_title_guess_questions
  add constraint party_title_guess_questions_difficulty_tier_check
  check (difficulty_tier between 1 and 5);

-- ----------------------------------------------------------------
-- 4. Ordered clue cards per question
-- ----------------------------------------------------------------
create table if not exists public.party_title_guess_clues (
  id bigint generated by default as identity primary key,
  question_id bigint not null
    references public.party_title_guess_questions(id) on delete cascade,
  character_id bigint not null
    references public.title_characters(id) on delete restrict,
  clue_order smallint not null
    check (clue_order between 1 and 4),
  clue_role_bucket text not null default 'supporting'
    check (clue_role_bucket in ('background', 'supporting', 'main-side', 'wildcard')),
  character_name_snapshot text not null default '',
  character_name_native_snapshot text,
  character_image_url_snapshot text,
  is_manual_override boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (question_id, clue_order),
  unique (question_id, character_id)
);

-- ----------------------------------------------------------------
-- 5. Optional likes for public/unlisted sets
-- ----------------------------------------------------------------
create table if not exists public.party_title_guess_set_likes (
  id bigint generated by default as identity primary key,
  set_id bigint not null
    references public.party_title_guess_sets(id) on delete cascade,
  user_id uuid not null
    references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (set_id, user_id)
);

-- ----------------------------------------------------------------
-- 6. Indexes
-- ----------------------------------------------------------------
create index if not exists idx_party_title_guess_sets_visibility_updated
  on public.party_title_guess_sets (visibility, updated_at desc);

create index if not exists idx_party_title_guess_sets_owner_updated
  on public.party_title_guess_sets (owner_user_id, updated_at desc);

create index if not exists idx_party_title_guess_sets_official_updated
  on public.party_title_guess_sets (is_official, updated_at desc);

create index if not exists idx_party_title_guess_questions_set_status_order
  on public.party_title_guess_questions (set_id, status, sort_order asc, id asc);

create index if not exists idx_party_title_guess_questions_answer_title
  on public.party_title_guess_questions (answer_title_id);

create index if not exists idx_party_title_guess_clues_question_order
  on public.party_title_guess_clues (question_id, clue_order asc);

create index if not exists idx_party_title_guess_clues_character
  on public.party_title_guess_clues (character_id);

create index if not exists idx_party_title_guess_set_likes_set
  on public.party_title_guess_set_likes (set_id);

create index if not exists idx_party_title_guess_set_likes_user
  on public.party_title_guess_set_likes (user_id);

-- ----------------------------------------------------------------
-- 7. updated_at triggers
-- ----------------------------------------------------------------
drop trigger if exists trg_party_title_guess_sets_updated_at
  on public.party_title_guess_sets;
create trigger trg_party_title_guess_sets_updated_at
  before update on public.party_title_guess_sets
  for each row execute function public.set_updated_at();

drop trigger if exists trg_party_title_guess_questions_updated_at
  on public.party_title_guess_questions;
create trigger trg_party_title_guess_questions_updated_at
  before update on public.party_title_guess_questions
  for each row execute function public.set_updated_at();

drop trigger if exists trg_party_title_guess_clues_updated_at
  on public.party_title_guess_clues;
create trigger trg_party_title_guess_clues_updated_at
  before update on public.party_title_guess_clues
  for each row execute function public.set_updated_at();

-- ----------------------------------------------------------------
-- 8. Counter sync helpers
-- ----------------------------------------------------------------
create or replace function public.sync_party_title_guess_question_count()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    update public.party_title_guess_sets
    set question_count = question_count + 1
    where id = new.set_id;
  elsif tg_op = 'DELETE' then
    update public.party_title_guess_sets
    set question_count = greatest(0, question_count - 1)
    where id = old.set_id;
  elsif tg_op = 'UPDATE' and new.set_id <> old.set_id then
    update public.party_title_guess_sets
    set question_count = greatest(0, question_count - 1)
    where id = old.set_id;

    update public.party_title_guess_sets
    set question_count = question_count + 1
    where id = new.set_id;
  end if;

  return null;
end;
$$;

drop trigger if exists trg_party_title_guess_questions_count
  on public.party_title_guess_questions;
create trigger trg_party_title_guess_questions_count
  after insert or delete or update of set_id on public.party_title_guess_questions
  for each row execute function public.sync_party_title_guess_question_count();

create or replace function public.sync_party_title_guess_like_count()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    update public.party_title_guess_sets
    set like_count = like_count + 1
    where id = new.set_id;
  elsif tg_op = 'DELETE' then
    update public.party_title_guess_sets
    set like_count = greatest(0, like_count - 1)
    where id = old.set_id;
  end if;

  return null;
end;
$$;

drop trigger if exists trg_party_title_guess_set_likes_count
  on public.party_title_guess_set_likes;
create trigger trg_party_title_guess_set_likes_count
  after insert or delete on public.party_title_guess_set_likes
  for each row execute function public.sync_party_title_guess_like_count();

create or replace function public.increment_party_title_guess_play_count(p_set_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.party_title_guess_sets
  set play_count = play_count + 1
  where id = p_set_id
    and (
      visibility in ('public', 'unlisted')
      or owner_user_id = auth.uid()
      or public.is_staff_user()
    );
end;
$$;

-- ----------------------------------------------------------------
-- 9. RLS
-- ----------------------------------------------------------------
alter table public.party_title_guess_sets enable row level security;
alter table public.party_title_guess_questions enable row level security;
alter table public.party_title_guess_clues enable row level security;
alter table public.party_title_guess_set_likes enable row level security;

drop policy if exists "Read party_title_guess_sets" on public.party_title_guess_sets;
create policy "Read party_title_guess_sets"
  on public.party_title_guess_sets for select
  using (
    public.is_staff_user()
    or visibility in ('public', 'unlisted')
    or owner_user_id = auth.uid()
  );

drop policy if exists "Create party_title_guess_sets" on public.party_title_guess_sets;
create policy "Create party_title_guess_sets"
  on public.party_title_guess_sets for insert
  with check (
    auth.uid() is not null
    and owner_user_id = auth.uid()
    and is_official = false
  );

drop policy if exists "Update party_title_guess_sets" on public.party_title_guess_sets;
create policy "Update party_title_guess_sets"
  on public.party_title_guess_sets for update
  using (
    owner_user_id = auth.uid()
    or public.is_staff_user()
  )
  with check (
    (owner_user_id = auth.uid() and is_official = false)
    or public.is_staff_user()
  );

drop policy if exists "Delete party_title_guess_sets" on public.party_title_guess_sets;
create policy "Delete party_title_guess_sets"
  on public.party_title_guess_sets for delete
  using (
    owner_user_id = auth.uid()
    or public.is_staff_user()
  );

drop policy if exists "Read party_title_guess_questions" on public.party_title_guess_questions;
create policy "Read party_title_guess_questions"
  on public.party_title_guess_questions for select
  using (
    public.is_staff_user()
    or exists (
      select 1
      from public.party_title_guess_sets s
      where s.id = party_title_guess_questions.set_id
        and (
          s.visibility in ('public', 'unlisted')
          or s.owner_user_id = auth.uid()
        )
    )
  );

drop policy if exists "Write party_title_guess_questions" on public.party_title_guess_questions;
create policy "Write party_title_guess_questions"
  on public.party_title_guess_questions for all
  using (
    public.is_staff_user()
    or exists (
      select 1
      from public.party_title_guess_sets s
      where s.id = party_title_guess_questions.set_id
        and s.owner_user_id = auth.uid()
    )
  )
  with check (
    public.is_staff_user()
    or exists (
      select 1
      from public.party_title_guess_sets s
      where s.id = party_title_guess_questions.set_id
        and s.owner_user_id = auth.uid()
    )
  );

drop policy if exists "Read party_title_guess_clues" on public.party_title_guess_clues;
create policy "Read party_title_guess_clues"
  on public.party_title_guess_clues for select
  using (
    public.is_staff_user()
    or exists (
      select 1
      from public.party_title_guess_questions q
      join public.party_title_guess_sets s on s.id = q.set_id
      where q.id = party_title_guess_clues.question_id
        and (
          s.visibility in ('public', 'unlisted')
          or s.owner_user_id = auth.uid()
        )
    )
  );

drop policy if exists "Write party_title_guess_clues" on public.party_title_guess_clues;
create policy "Write party_title_guess_clues"
  on public.party_title_guess_clues for all
  using (
    public.is_staff_user()
    or exists (
      select 1
      from public.party_title_guess_questions q
      join public.party_title_guess_sets s on s.id = q.set_id
      where q.id = party_title_guess_clues.question_id
        and s.owner_user_id = auth.uid()
    )
  )
  with check (
    public.is_staff_user()
    or exists (
      select 1
      from public.party_title_guess_questions q
      join public.party_title_guess_sets s on s.id = q.set_id
      where q.id = party_title_guess_clues.question_id
        and s.owner_user_id = auth.uid()
    )
  );

drop policy if exists "Read party_title_guess_set_likes" on public.party_title_guess_set_likes;
create policy "Read party_title_guess_set_likes"
  on public.party_title_guess_set_likes for select
  using (true);

drop policy if exists "Like party_title_guess_sets" on public.party_title_guess_set_likes;
create policy "Like party_title_guess_sets"
  on public.party_title_guess_set_likes for insert
  with check (
    auth.uid() is not null
    and user_id = auth.uid()
    and exists (
      select 1
      from public.party_title_guess_sets s
      where s.id = party_title_guess_set_likes.set_id
        and s.visibility in ('public', 'unlisted')
    )
  );

drop policy if exists "Unlike party_title_guess_sets" on public.party_title_guess_set_likes;
create policy "Unlike party_title_guess_sets"
  on public.party_title_guess_set_likes for delete
  using (
    user_id = auth.uid()
    or public.is_staff_user()
  );

