create table if not exists public.party_song_presets (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  description text,
  status text not null default 'draft' check (status in ('draft', 'published', 'archived')),
  visibility text not null default 'public' check (visibility in ('public', 'private')),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.party_song_preset_items (
  id bigint generated by default as identity primary key,
  preset_id bigint not null references public.party_song_presets(id) on delete cascade,
  song_id bigint not null,
  source_title_id bigint,
  source_title_name text not null default '',
  song_title text not null default '',
  theme_type text not null default 'OP',
  artist_name text,
  media_url text not null default '',
  cover_url text,
  position integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (preset_id, song_id)
);

create index if not exists idx_party_song_presets_status_visibility
on public.party_song_presets(status, visibility, updated_at desc);

create index if not exists idx_party_song_preset_items_preset_position
on public.party_song_preset_items(preset_id, position asc, created_at asc);

create index if not exists idx_party_song_preset_items_song
on public.party_song_preset_items(song_id);

drop trigger if exists trg_party_song_presets_updated_at on public.party_song_presets;
create trigger trg_party_song_presets_updated_at
before update on public.party_song_presets
for each row
execute function public.set_updated_at();

drop trigger if exists trg_party_song_preset_items_updated_at on public.party_song_preset_items;
create trigger trg_party_song_preset_items_updated_at
before update on public.party_song_preset_items
for each row
execute function public.set_updated_at();

alter table if exists public.party_song_presets enable row level security;
alter table if exists public.party_song_preset_items enable row level security;

drop policy if exists "Read party song presets" on public.party_song_presets;
create policy "Read party song presets"
on public.party_song_presets for select
using (
  (select public.is_staff_user())
  or (
    status = 'published'
    and visibility = 'public'
  )
);

drop policy if exists "Staff can write party song presets" on public.party_song_presets;
create policy "Staff can write party song presets"
on public.party_song_presets for insert
with check ((select public.is_staff_user()));

drop policy if exists "Staff can update party song presets" on public.party_song_presets;
create policy "Staff can update party song presets"
on public.party_song_presets for update
using ((select public.is_staff_user()))
with check ((select public.is_staff_user()));

drop policy if exists "Staff can delete party song presets" on public.party_song_presets;
create policy "Staff can delete party song presets"
on public.party_song_presets for delete
using ((select public.is_staff_user()));

drop policy if exists "Read party song preset items" on public.party_song_preset_items;
create policy "Read party song preset items"
on public.party_song_preset_items for select
using (
  (select public.is_staff_user())
  or exists (
    select 1
    from public.party_song_presets preset
    where preset.id = party_song_preset_items.preset_id
      and preset.status = 'published'
      and preset.visibility = 'public'
  )
);

drop policy if exists "Staff can write party song preset items" on public.party_song_preset_items;
create policy "Staff can write party song preset items"
on public.party_song_preset_items for insert
with check ((select public.is_staff_user()));

drop policy if exists "Staff can update party song preset items" on public.party_song_preset_items;
create policy "Staff can update party song preset items"
on public.party_song_preset_items for update
using ((select public.is_staff_user()))
with check ((select public.is_staff_user()));

drop policy if exists "Staff can delete party song preset items" on public.party_song_preset_items;
create policy "Staff can delete party song preset items"
on public.party_song_preset_items for delete
using ((select public.is_staff_user()));
