-- ============================================================
-- Party Song Templates  (v1: catalog-only, no YouTube)
-- ============================================================
-- party_song_templates       – template header
-- party_song_template_items  – denormalized song rows (matches preset_items shape)
-- party_template_likes       – per-user like tracking + counter trigger
-- ============================================================

-- ----------------------------------------------------------------
-- 1. party_song_templates
-- ----------------------------------------------------------------
create table if not exists public.party_song_templates (
  id              bigint generated by default as identity primary key,
  owner_user_id   uuid references auth.users(id) on delete set null,
  creator_name    text not null default '',           -- denormalized display name
  name            text not null,
  description     text,
  cover_url       text,
  visibility      text not null default 'public'
                    check (visibility in ('public', 'unlisted', 'private')),
  mode_scope      text not null default 'all'
                    check (mode_scope in ('all', 'quiz', 'vote')),
  source_type     text not null default 'catalog'
                    check (source_type in ('catalog')),  -- 'youtube' reserved for v2
  is_official     boolean not null default false,
  tags            text[]  not null default '{}',
  like_count      integer not null default 0,
  view_count      integer not null default 0,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

-- ----------------------------------------------------------------
-- 2. party_song_template_items  (denormalized — same shape as preset_items)
-- ----------------------------------------------------------------
create table if not exists public.party_song_template_items (
  id                bigint generated by default as identity primary key,
  template_id       bigint not null
                      references public.party_song_templates(id) on delete cascade,
  song_id           bigint not null,
  source_title_id   bigint,
  source_title_name text not null default '',
  song_title        text not null default '',
  theme_type        text not null default 'OP',
  artist_name       text,
  media_url         text not null default '',
  cover_url         text,
  position          integer not null default 0,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  unique (template_id, song_id)
);

-- ----------------------------------------------------------------
-- 3. party_template_likes  (per-user; trigger keeps like_count synced)
-- ----------------------------------------------------------------
create table if not exists public.party_template_likes (
  id          bigint generated by default as identity primary key,
  template_id bigint not null
                references public.party_song_templates(id) on delete cascade,
  user_id     uuid  not null
                references auth.users(id) on delete cascade,
  created_at  timestamptz not null default now(),
  unique (template_id, user_id)
);

-- ----------------------------------------------------------------
-- 4. Indexes
-- ----------------------------------------------------------------
create index if not exists idx_party_song_templates_visibility_updated
  on public.party_song_templates(visibility, updated_at desc);

create index if not exists idx_party_song_templates_owner
  on public.party_song_templates(owner_user_id);

create index if not exists idx_party_song_templates_official
  on public.party_song_templates(is_official, updated_at desc);

create index if not exists idx_party_song_templates_mode_scope
  on public.party_song_templates(mode_scope);

create index if not exists idx_party_song_template_items_template_position
  on public.party_song_template_items(template_id, position asc, created_at asc);

create index if not exists idx_party_song_template_items_song
  on public.party_song_template_items(song_id);

create index if not exists idx_party_template_likes_template
  on public.party_template_likes(template_id);

create index if not exists idx_party_template_likes_user
  on public.party_template_likes(user_id);

-- ----------------------------------------------------------------
-- 5. updated_at triggers
-- ----------------------------------------------------------------
drop trigger if exists trg_party_song_templates_updated_at
  on public.party_song_templates;
create trigger trg_party_song_templates_updated_at
  before update on public.party_song_templates
  for each row execute function public.set_updated_at();

drop trigger if exists trg_party_song_template_items_updated_at
  on public.party_song_template_items;
create trigger trg_party_song_template_items_updated_at
  before update on public.party_song_template_items
  for each row execute function public.set_updated_at();

-- ----------------------------------------------------------------
-- 6. like_count sync trigger
-- ----------------------------------------------------------------
create or replace function public.sync_party_template_like_count()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    update public.party_song_templates
    set like_count = like_count + 1
    where id = new.template_id;
  elsif tg_op = 'DELETE' then
    update public.party_song_templates
    set like_count = greatest(0, like_count - 1)
    where id = old.template_id;
  end if;
  return null;
end;
$$;

drop trigger if exists trg_party_template_likes_count
  on public.party_template_likes;
create trigger trg_party_template_likes_count
  after insert or delete on public.party_template_likes
  for each row execute function public.sync_party_template_like_count();

-- ----------------------------------------------------------------
-- 7. increment_template_view_count (called from client/RPC)
-- ----------------------------------------------------------------
create or replace function public.increment_template_view_count(p_template_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.party_song_templates
  set view_count = view_count + 1
  where id = p_template_id
    and (
      visibility in ('public', 'unlisted')
      or owner_user_id = auth.uid()
      or (select public.is_staff_user())
    );
end;
$$;

-- ----------------------------------------------------------------
-- 8. RLS — enable
-- ----------------------------------------------------------------
alter table if exists public.party_song_templates     enable row level security;
alter table if exists public.party_song_template_items enable row level security;
alter table if exists public.party_template_likes      enable row level security;

-- ================================================================
-- RLS: party_song_templates
-- ================================================================

-- SELECT: public/unlisted visible to all; private only to owner + staff
drop policy if exists "Read party_song_templates" on public.party_song_templates;
create policy "Read party_song_templates"
  on public.party_song_templates for select
  using (
    (select public.is_staff_user())
    or visibility in ('public', 'unlisted')
    or owner_user_id = auth.uid()
  );

-- INSERT: any authenticated user (owner = self)
drop policy if exists "Create party_song_templates" on public.party_song_templates;
create policy "Create party_song_templates"
  on public.party_song_templates for insert
  with check (
    auth.uid() is not null
    and owner_user_id = auth.uid()
    and is_official = false   -- only staff may set is_official
  );

-- UPDATE: owner may update their own (except is_official); staff may update all
drop policy if exists "Update party_song_templates" on public.party_song_templates;
create policy "Update party_song_templates"
  on public.party_song_templates for update
  using (
    owner_user_id = auth.uid()
    or (select public.is_staff_user())
  )
  with check (
    (owner_user_id = auth.uid() and is_official = false)
    or (select public.is_staff_user())
  );

-- DELETE: owner or staff
drop policy if exists "Delete party_song_templates" on public.party_song_templates;
create policy "Delete party_song_templates"
  on public.party_song_templates for delete
  using (
    owner_user_id = auth.uid()
    or (select public.is_staff_user())
  );

-- ================================================================
-- RLS: party_song_template_items  (inherits parent visibility)
-- ================================================================

drop policy if exists "Read party_song_template_items" on public.party_song_template_items;
create policy "Read party_song_template_items"
  on public.party_song_template_items for select
  using (
    (select public.is_staff_user())
    or exists (
      select 1
      from public.party_song_templates t
      where t.id = party_song_template_items.template_id
        and (
          t.visibility in ('public', 'unlisted')
          or t.owner_user_id = auth.uid()
        )
    )
  );

drop policy if exists "Write party_song_template_items" on public.party_song_template_items;
create policy "Write party_song_template_items"
  on public.party_song_template_items for insert
  with check (
    (select public.is_staff_user())
    or exists (
      select 1
      from public.party_song_templates t
      where t.id = party_song_template_items.template_id
        and t.owner_user_id = auth.uid()
    )
  );

drop policy if exists "Update party_song_template_items" on public.party_song_template_items;
create policy "Update party_song_template_items"
  on public.party_song_template_items for update
  using (
    (select public.is_staff_user())
    or exists (
      select 1
      from public.party_song_templates t
      where t.id = party_song_template_items.template_id
        and t.owner_user_id = auth.uid()
    )
  )
  with check (
    (select public.is_staff_user())
    or exists (
      select 1
      from public.party_song_templates t
      where t.id = party_song_template_items.template_id
        and t.owner_user_id = auth.uid()
    )
  );

drop policy if exists "Delete party_song_template_items" on public.party_song_template_items;
create policy "Delete party_song_template_items"
  on public.party_song_template_items for delete
  using (
    (select public.is_staff_user())
    or exists (
      select 1
      from public.party_song_templates t
      where t.id = party_song_template_items.template_id
        and t.owner_user_id = auth.uid()
    )
  );

-- ================================================================
-- RLS: party_template_likes
-- ================================================================

-- Everyone can read likes (for like counts / UI state)
drop policy if exists "Read party_template_likes" on public.party_template_likes;
create policy "Read party_template_likes"
  on public.party_template_likes for select
  using (true);

-- Authenticated users can like public/unlisted templates (once each, enforced by unique)
drop policy if exists "Like party_template" on public.party_template_likes;
create policy "Like party_template"
  on public.party_template_likes for insert
  with check (
    auth.uid() is not null
    and user_id = auth.uid()
    and exists (
      select 1
      from public.party_song_templates t
      where t.id = party_template_likes.template_id
        and t.visibility in ('public', 'unlisted')
    )
  );

-- Users can only unlike their own likes
drop policy if exists "Unlike party_template" on public.party_template_likes;
create policy "Unlike party_template"
  on public.party_template_likes for delete
  using (
    user_id = auth.uid()
    or (select public.is_staff_user())
  );
