create table if not exists public.content_reports (
  id bigint generated by default as identity primary key,
  title_id bigint not null references public.canonical_titles(id) on delete cascade,
  reported_by uuid references auth.users(id) on delete set null,
  issue_type text not null
    check (issue_type in ('metadata', 'broken_link', 'wrong_cover', 'duplicate', 'nsfw', 'other')),
  status text not null default 'open'
    check (status in ('open', 'in_review', 'resolved', 'dismissed')),
  source_context text not null default 'title_detail'
    check (source_context in ('title_detail', 'title_card', 'admin', 'other')),
  description text,
  internal_note text,
  assigned_to uuid references auth.users(id) on delete set null,
  resolved_at timestamptz,
  resolved_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_content_reports_status_created
on public.content_reports(status, created_at desc);

create index if not exists idx_content_reports_issue_type_created
on public.content_reports(issue_type, created_at desc);

create index if not exists idx_content_reports_title
on public.content_reports(title_id, created_at desc);

create index if not exists idx_content_reports_assigned_status
on public.content_reports(assigned_to, status, created_at desc);

drop trigger if exists trg_content_reports_updated_at on public.content_reports;
create trigger trg_content_reports_updated_at
before update on public.content_reports
for each row
execute function public.set_updated_at();

alter table if exists public.content_reports enable row level security;

drop policy if exists "Authenticated users can submit content reports" on public.content_reports;
create policy "Authenticated users can submit content reports"
on public.content_reports for insert
to authenticated
with check (
  auth.uid() is not null
  and (reported_by is null or reported_by = auth.uid())
);

drop policy if exists "Users can read own content reports" on public.content_reports;
create policy "Users can read own content reports"
on public.content_reports for select
to authenticated
using (
  reported_by = auth.uid()
);

drop policy if exists "Staff can manage content reports" on public.content_reports;
create policy "Staff can manage content reports"
on public.content_reports for all
using (public.is_staff_user())
with check (public.is_staff_user());
