create extension if not exists pgcrypto;

create table if not exists canonical_titles (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  canonical_title text not null,
  type text not null check (type in ('anime', 'manga')),
  subtype text not null default 'anime' check (subtype in ('anime', 'manga', 'manhwa', 'manhua', 'webtoon')),
  origin_country text,
  origin_language text,
  status text default 'ongoing' check (status in ('ongoing', 'completed', 'upcoming', 'hiatus', 'cancelled')),
  release_year integer,
  episodes integer,
  chapters integer,
  volumes integer,
  duration_minutes integer,
  is_adult boolean not null default false,
  cover_image text,
  banner_image text,
  synopsis text,
  avg_score numeric(5,2),
  popularity_score numeric(12,2),
  editorial_score numeric(5,2),
  raw_payload jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_synced_at timestamptz
);

create table if not exists title_aliases (
  id bigint generated by default as identity primary key,
  canonical_title_id bigint not null references canonical_titles(id) on delete cascade,
  alias text not null,
  language_code text,
  alias_type text not null default 'alternate' check (alias_type in ('canonical', 'english', 'romaji', 'native', 'localized', 'synonym')),
  is_primary boolean not null default false,
  source_provider text,
  created_at timestamptz not null default now()
);

create table if not exists title_source_refs (
  id bigint generated by default as identity primary key,
  canonical_title_id bigint not null references canonical_titles(id) on delete cascade,
  provider text not null check (provider in ('anilist', 'mangadex', 'kitsu', 'jikan', 'manual')),
  external_id text not null,
  external_url text,
  source_priority integer not null default 100,
  raw_payload jsonb,
  fetched_at timestamptz not null default now(),
  last_synced_at timestamptz not null default now(),
  unique (provider, external_id)
);

create table if not exists title_genres (
  id bigint generated by default as identity primary key,
  canonical_title_id bigint not null references canonical_titles(id) on delete cascade,
  genre_name text not null,
  normalized_name text generated always as (lower(genre_name)) stored,
  unique (canonical_title_id, normalized_name)
);

create table if not exists title_tags (
  id bigint generated by default as identity primary key,
  canonical_title_id bigint not null references canonical_titles(id) on delete cascade,
  tag_name text not null,
  normalized_name text generated always as (lower(tag_name)) stored,
  weight numeric(5,2),
  source_provider text,
  unique (canonical_title_id, normalized_name)
);

create table if not exists title_relations (
  id bigint generated by default as identity primary key,
  source_title_id bigint not null references canonical_titles(id) on delete cascade,
  target_title_id bigint not null references canonical_titles(id) on delete cascade,
  relation_type text not null check (relation_type in ('sequel', 'prequel', 'adaptation', 'side_story', 'shared_universe', 'related')),
  source_provider text,
  unique (source_title_id, target_title_id, relation_type)
);

create table if not exists title_availability (
  id bigint generated by default as identity primary key,
  canonical_title_id bigint not null references canonical_titles(id) on delete cascade,
  platform_name text not null,
  region_code text,
  url text not null,
  is_official boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists moods (
  id text primary key,
  name_th text not null,
  name_en text not null,
  icon text,
  color text,
  description text
);

create table if not exists title_moods (
  canonical_title_id bigint not null references canonical_titles(id) on delete cascade,
  mood_id text not null references moods(id) on delete cascade,
  primary key (canonical_title_id, mood_id)
);

alter table if exists title_genres
  add column if not exists canonical_title_id bigint;

alter table if exists title_tags
  add column if not exists canonical_title_id bigint;

alter table if exists title_moods
  add column if not exists canonical_title_id bigint;

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public' and table_name = 'title_genres' and column_name = 'canonical_title_id'
  ) then
    begin
      alter table public.title_genres
        add constraint title_genres_canonical_title_id_fkey
        foreign key (canonical_title_id) references public.canonical_titles(id) on delete cascade;
    exception when duplicate_object then null;
    end;
  end if;
end $$;

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public' and table_name = 'title_tags' and column_name = 'canonical_title_id'
  ) then
    begin
      alter table public.title_tags
        add constraint title_tags_canonical_title_id_fkey
        foreign key (canonical_title_id) references public.canonical_titles(id) on delete cascade;
    exception when duplicate_object then null;
    end;
  end if;
end $$;

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public' and table_name = 'title_moods' and column_name = 'canonical_title_id'
  ) then
    begin
      alter table public.title_moods
        add constraint title_moods_canonical_title_id_fkey
        foreign key (canonical_title_id) references public.canonical_titles(id) on delete cascade;
    exception when duplicate_object then null;
    end;
  end if;
end $$;

create table if not exists catalog_sync_runs (
  id bigint generated by default as identity primary key,
  provider text not null check (provider in ('anilist', 'mangadex', 'kitsu', 'jikan', 'manual', 'all')),
  run_type text not null default 'ingest' check (run_type in ('ingest', 'enrichment', 'reconcile', 'audit')),
  status text not null default 'running' check (status in ('running', 'completed', 'failed')),
  records_processed integer not null default 0,
  error_message text,
  started_at timestamptz not null default now(),
  finished_at timestamptz
);

create table if not exists catalog_merge_queue (
  id bigint generated by default as identity primary key,
  source_title_id bigint not null references canonical_titles(id) on delete cascade,
  candidate_title_id bigint not null references canonical_titles(id) on delete cascade,
  confidence numeric(5,2),
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  reason text,
  created_at timestamptz not null default now(),
  reviewed_at timestamptz
);

create index if not exists idx_canonical_titles_type on canonical_titles(type, subtype);
create index if not exists idx_canonical_titles_status on canonical_titles(status);
create index if not exists idx_canonical_titles_release_year on canonical_titles(release_year desc);
create index if not exists idx_canonical_titles_popularity on canonical_titles(popularity_score desc nulls last);
create index if not exists idx_title_aliases_title_id on title_aliases(canonical_title_id);
create unique index if not exists idx_title_aliases_unique_value on title_aliases (canonical_title_id, alias, coalesce(language_code, ''), alias_type);
create index if not exists idx_title_source_refs_title_id on title_source_refs(canonical_title_id);
create index if not exists idx_title_source_refs_provider on title_source_refs(provider, source_priority);
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'title_genres' and column_name = 'canonical_title_id'
  ) then
    execute 'create index if not exists idx_title_genres_title_id on public.title_genres(canonical_title_id)';
  end if;
end $$;

do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'title_tags' and column_name = 'canonical_title_id'
  ) then
    execute 'create index if not exists idx_title_tags_title_id on public.title_tags(canonical_title_id)';
  end if;
end $$;

create index if not exists idx_title_availability_title_id on title_availability(canonical_title_id);
create unique index if not exists idx_title_availability_unique_value on title_availability (canonical_title_id, platform_name, coalesce(region_code, ''), url);
create index if not exists idx_catalog_sync_runs_provider on catalog_sync_runs(provider, started_at desc);
create index if not exists idx_catalog_merge_queue_status on catalog_merge_queue(status, confidence desc nulls last);

create or replace view catalog_titles_view as
select
  ct.id,
  ct.slug,
  ct.canonical_title,
  ct.type,
  ct.subtype,
  ct.origin_country,
  ct.origin_language,
  ct.status,
  ct.release_year,
  ct.episodes,
  ct.chapters,
  ct.volumes,
  ct.duration_minutes,
  ct.is_adult,
  ct.cover_image,
  ct.banner_image,
  ct.synopsis,
  ct.avg_score,
  ct.popularity_score,
  ct.editorial_score,
  ct.last_synced_at,
  array_remove(array_agg(distinct tg.genre_name), null) as genres,
  array_remove(array_agg(distinct tt.tag_name), null) as tags
from canonical_titles ct
left join title_genres tg on tg.canonical_title_id = ct.id
left join title_tags tt on tt.canonical_title_id = ct.id
group by ct.id;

create or replace function set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_canonical_titles_updated_at on canonical_titles;
create trigger trg_canonical_titles_updated_at
before update on canonical_titles
for each row
execute function set_updated_at();
